#!/usr/bin/env bash
# Генератор CI-файла проекта из профиля (контракт 063, ветвь (а)):
# bash scripts/gen_ci_workflow.sh --repo <корень> пишет джобу `harness` в
# объявленный профилью ci.workflow по правилам И-4, И-5, И-6, И-8, И-9, И-10.
#
# Коды возврата:
#   0 — успех (профиль не объявляет ci.workflow → «некуда» rc 0, ничего
#       не пишется; профиль не объявляет команд/барьеров → vacuous, файл-цель
#       не тронут);
#   1 — именованный отказ с фразой на stderr (stdout пуст);
#   2 — NOT_IMPLEMENTED.
set -uo pipefail

export PATH=/usr/bin:/bin
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
      GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_TEMPLATE_DIR GIT_CEILING_DIRECTORIES
export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESOLVER="$SELF_DIR/profile_resolver.sh"

usage() {
  printf 'ci-генератор ОТКАЗ: usage: bash scripts/gen_ci_workflow.sh --repo <корень>\n' >&2
  exit 1
}

REPO=""
while [ $# -gt 0 ]; do
  case "$1" in
    --repo) REPO="${2:?}"; shift 2 ;;
    --help|-h) usage ;;
    *) printf 'ci-генератор ОТКАЗ: неизвестный аргумент: %s\n' "$1" >&2; usage ;;
  esac
done

[ -n "$REPO" ] || usage
[ -d "$REPO" ] || { printf 'ci-генератор ОТКАЗ: каталог репо не существует: %s\n' "$REPO" >&2; exit 1; }

command -v git >/dev/null 2>&1 || { printf 'NOT_IMPLEMENTED: нет git\n' >&2; exit 2; }
command -v jq  >/dev/null 2>&1 || { printf 'NOT_IMPLEMENTED: нет jq\n' >&2; exit 2; }
command -v awk >/dev/null 2>&1 || { printf 'NOT_IMPLEMENTED: нет awk\n' >&2; exit 2; }

# Единый резолв профиля (И-8). Отказ резолвера → rc 1 с дословным прокси stderr.
PROFILE="$(HARNESS_PROJECT_LAYER_ROOT="${HARNESS_PROJECT_LAYER_ROOT:-}" \
           bash "$RESOLVER" --repo "$REPO" 2>&1)" \
  || { printf '%s\n' "$PROFILE" >&2; exit 1; }

# ci.workflow — относительный путь от корня репо. Если не объявлен → rc 0,
# «некуда генерировать», ничего не пишется (И-5).
CW="$(printf '%s' "$PROFILE" | jq -r '.ci.value.workflow // empty')"
[ -n "$CW" ] || {
  printf 'ci-генератор: профиль не объявляет ci.workflow — генерировать некуда\n' >&2
  exit 0
}

FIX="$(printf '%s' "$PROFILE" | jq -r '.workflowPaths.fixtures.value // empty')"
[ -n "$FIX" ] || {
  printf 'ci-генератор ОТКАЗ: профиль не объявляет workflowPaths.fixtures — путь барьеров неизвестен\n' >&2
  exit 1
}

# Сбор объявленных команд и барьеров.
declare -a COMMANDS=()     # "<ключ>|<значение>"
declare -a BARRIERS=()     # "<имя>"
for k in test build typecheck lint; do
  v="$(printf '%s' "$PROFILE" | jq -r --arg k "$k" '.commands[$k].value // empty')"
  [ -n "$v" ] && COMMANDS+=("$k|$v")
done
# barriers.mandatory — массив строк (резолвер 054 уже валидировал класс имени).
while IFS= read -r b; do
  [ -n "$b" ] || continue
  BARRIERS+=("$b")
done < <(printf '%s' "$PROFILE" | jq -r '.barriers.mandatory.value[]? // empty' 2>/dev/null)

# Барьер без файла в дереве → rc 1 дословно, файл-цель НЕ трогаем.
for b in "${BARRIERS[@]:-}"; do
  [ -n "$b" ] || continue
  [ -f "$REPO/$FIX/$b.sh" ] \
    || { printf 'ci-генератор ОТКАЗ: объявленный барьер отсутствует в дереве: %s (%s/%s.sh)\n' "$b" "$FIX" "$b" >&2; exit 1; }
done

# Vacuous: ни команд, ни барьеров → rc 0, фраза, файл-цель байт-в-байт неизменен.
if [ "${#COMMANDS[@]}" -eq 0 ] && [ "${#BARRIERS[@]}" -eq 0 ]; then
  printf 'ci-генератор: профиль не объявляет команд и барьеров — vacuous, файл не тронут\n' >&2
  exit 0
fi

TARGET="$REPO/$CW"
mkdir -p "$(dirname "$TARGET")"

# ── Рендер файла-цели по закрытой форме И-10 ───────────────────────────────
# Контур (ЛИТЕРАЛ, арбитраж 063-Б4): первые 9 строк — безусловно.
# Шаги И-4: каждая объявленная команда → - name: commands.<ключ> + run: | (тело
# с отступом 10 пробелов); каждый барьер → - name: barriers.<имя> + run: |
# + строка `          bash <FIX>/<имя>.sh` (отступ 10). Шаг переноса несёт
# ровно ДВА ключа — `name` и `run`; тело шага — строки самой команды.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
{
  printf '# GENERATED by dev-harness gen_ci_workflow — не править руками; источник — harness.project.json\n'
  printf 'name: harness\n'
  printf 'on: [push, pull_request]\n'
  printf 'jobs:\n'
  printf '  harness:\n'
  printf '    runs-on: ubuntu-latest\n'
  printf '    steps:\n'
  printf '      - uses: actions/checkout@v4\n'
  for entry in "${COMMANDS[@]}"; do
    k="${entry%%|*}"
    v="${entry#*|}"
    printf '      - name: commands.%s\n' "$k"
    printf '        run: |\n'
    # Каждая строка команды — с отступом ровно 10 пробелов. Многострочная
    # команда: каждая строка с тем же отступом.
    printf '%s\n' "$v" | awk '{ printf "          %s\n", $0 }'
  done
  for b in "${BARRIERS[@]}"; do
    [ -n "$b" ] || continue
    printf '      - name: barriers.%s\n' "$b"
    printf '        run: |\n'
    printf '          bash %s/%s.sh\n' "$FIX" "$b"
  done
} > "$TMP"

# Детерминированная запись (И-6): побайтово.
mv "$TMP" "$TARGET"
trap - EXIT
exit 0
